version: '3'

services:
  fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - be
    env_file:
      - .env

  be:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:5000"
    env_file:
      - .env
